language: node_js
node_js:
- 8
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: outsideris@gmail.com
  api_key:
    secure: GO0Lbv47vgoCWjVt9hLPN9ypW8Qd8F70jMVvlrlVP+U38g2VpG9smV6Sb5DbUSdLf8PS99lgfYG6lkmpgHPjbXAQCeydpB8r6o54efkMOXbG3TYaUnIa+LmJFAwYT+cW2S2DkBczwgJVkewwb/Y96ej6cFeYmzMepOAf4g56WwTvdQ3pv2dcpkf7AxaAu+kkF5EiMSC31YFgI0pOie2DoadjUqQ8dwM9eXplmek/dkuzHU/it/2klHPr41Izcmgm5VXQOqCzI5NtxesVr8BhDhLgaAen0HS2iGXRULegmZDsD4FkhT85fdBIW35z1n+cSFs+gG/iUDU3Jm/ClRqfTvYAHODdmQ/YlqXSb4o8YNlmiv0swtgTfSro+WWzIJSK0K7g3sz02ZMzmG66QCFIimok+n6jNdwuePZFZ/7k85LVQwz0lVDBzEOA+pmrNrwhmNvZ2foYWYbIvNBI3NxrV1/6A8VIzaG4ZuhLnpO9Rb6VR9FbTiGlePFzhXWUj4tV6P+A8WJY+Y9oZ8vioUkGGp2gEVj1rk67cr5EwHUQrJ+am7qCdi9HNQIEYhQkJ75vWbZV5Nn1uif8GOz1odNzMJu81NpvQDJ3FzN+USmtWmglPif9JHekAgcQ+HwZqAChPnQuDa0ZRttISV+Wkg5r9rlXJ6HocUJj95WX6lfICSI=
  on:
    all_branches: true
    tags: true
    repo: outsideris/jate
